// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMG9xMbOkWTOuT-U7gg7ws00PhgMmwmQU',
    appId: '1:461620076824:web:cf3c0ab88d4c367e053e6d',
    messagingSenderId: '461620076824',
    projectId: 'alta-mini-project',
    authDomain: 'alta-mini-project.firebaseapp.com',
    storageBucket: 'alta-mini-project.appspot.com',
    measurementId: 'G-PCRN5ZPFWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcQ1zhg8e_EZURCqPv9EzBbMrsX9WGSE',
    appId: '1:461620076824:android:d41b6731a872bc3e053e6d',
    messagingSenderId: '461620076824',
    projectId: 'alta-mini-project',
    storageBucket: 'alta-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHyehhq3WjTM3mSAyIds8JXPx4FEBoHs',
    appId: '1:461620076824:ios:73f80bb3ecb37ba6053e6d',
    messagingSenderId: '461620076824',
    projectId: 'alta-mini-project',
    storageBucket: 'alta-mini-project.appspot.com',
    iosClientId: '461620076824-qujol8p31mkf95jo4h19sm18j1fgagej.apps.googleusercontent.com',
    iosBundleId: 'com.example.altaMiniProject',
  );
}
